Mob 6589 fix http options matching
careem/laravel-prometheus-exporter pull request #12
Opened 2022-03-23 12:14 UTC by mohamed-wagdy-careem

2022-03-23 12:40 UTC, m-abdelmohsen commented on src/PrometheusLumenFastRouteMiddleware.php
>          $method = $method == 'HEAD' ? 'GET' : $method;
I believe we need to do the same for the OPTIONS

2022-03-23 12:41 UTC, m-abdelmohsen commented on src/PrometheusLumenFastRouteMiddleware.php
> +            $corsPreflightRequestMethod = $request->headers->get('Access-Control-Request-Method');
why not to move that up and try to do the match once

2022-03-23 14:04 UTC, mohamed-wagdy-careem commented on src/PrometheusLumenFastRouteMiddleware.php
> +            $corsPreflightRequestMethod = $request->headers->get('Access-Control-Request-Method');
updated the implementation

2022-03-24 13:23 UTC, WaseemAtCareem requested changes
First review comments

2022-03-24 13:28 UTC, mohamed-wagdy-careem commented on composer.json
> +        "nikic/fast-route": "^1.3"
Fast route is used in the middleware that we added earlier. It works without it since the dependency is required by lumen as well. I added it to let unit tests run.

2022-03-29 05:58 UTC, merged