Fix WorkerServiceProvider event listner
careem/laravel-prometheus-exporter pull request #7
Opened 2021-01-10 10:52 UTC by houssainy

WorkerStopping event doesn't have an instance of the job, so job->resolveName()
and job->getQueue() were failing. Instead get the job name and queue name while
the job in processing state (JobProcessing event).

2021-01-10 11:07 UTC, shameer-chathangal commented on src/WorkerServiceProvider.php
> +                // fail silently and don't stop the application
@m-abdelmohsen Any idea what are the chances reaching here?

2021-01-10 11:10 UTC, FezKazi approved these changes

2021-01-10 11:14 UTC, FezKazi approved these changes
Thanks for adding a default too. I was thinking of it this morning.

Also:
Might be worth extracting the status and error codes to an enum or map

2021-01-10 11:14 UTC, FezKazi commented on src/WorkerServiceProvider.php
> +                        $errorCode = -1;
Might be worth extracting the status and error codes to an enum or map

2021-01-10 11:17 UTC, WaseemAtCareem requested changes
Storing data about job, consider using Reflection or implementing custom interface for data collection

2021-01-10 11:17 UTC, WaseemAtCareem commented on src/WorkerServiceProvider.php
>          });
These values will change on every job, hence, those public static vars are not helpful and could be misleading to as multiple jobs are launched when worker process gets executed

2021-01-10 12:38 UTC, nerac requested changes
I think we should log the exception to go live with this.

2021-01-10 12:38 UTC, nerac commented on src/WorkerServiceProvider.php
>          });
@WaseemAtCareem You mean that these values are global hence they will be overwritten? Or they will be static per job running?

2021-01-10 12:38 UTC, nerac commented on src/WorkerServiceProvider.php
> +                        $errorCode = -1;
These values will go to our Argus, if an engineer sees -1 will not understand what he's seeing nor know where to get the documentation. I think would be easier to structure the reporting like this:
```
{...status:"failure", errorType:"exception"...}
{...status:"success", ...}
```
Something like this will let us know immediately on prometheus that is or is not an error and classify the errors based on the type (exception, timeout, etc..). I would not include the message because will spread to many records in Prometheus.

2021-01-10 12:38 UTC, nerac commented on src/WorkerServiceProvider.php
> +                // fail silently and don't stop the application
I think we can fail silently but, clearly, we need to report this somewhere else how we'll see it if something goes wrong here? At least we should have a log here.

Following what Shameer said, are we 100% we should fail silently here? Maybe is worthy to fail and let the worker restart, in any case this must be reported IMO.

2021-01-10 12:44 UTC, RFcareem commented on src/WorkerServiceProvider.php
> +                // fail silently and don't stop the application
+1 for the log message here

2021-01-10 12:51 UTC, houssainy commented on src/WorkerServiceProvider.php
>          });
@m-abdelmohsen and I had this discussion, but we decided to go forward with the static solution with taking the advantage that PHP is single threaded. and since that we are sure that each process is handling only one job from JobProcessing to JobProcessed or JobFailed ...etc we are sure that these static values will not get overwritten by another thread. 

Personally, I don't prefer to use the static fields, but the problem that this is the only solution we have for now. @WaseemAtCareem @nerac do you have any suggestions?

2021-01-10 13:19 UTC, nerac commented on src/WorkerServiceProvider.php
>          });
This is a side-effect so it can be a problem if you have concurrent access to it but if that's not the case and we are 100% sure I won't bother on changing it.

2021-01-10 13:32 UTC, WaseemAtCareem commented on src/WorkerServiceProvider.php
>          });
@nerac yes, I meant those static class variables and will get replaced on every job run.
@houssainy we can live with that compromise, however, please note Laravel worker do support processing multiple jobs by single worker instance but these days we launch separate instances per connection.

2021-01-10 14:17 UTC, nerac commented on src/WorkerServiceProvider.php
>          });
In any case, why do we need this to be static and public? Are we consuming these values from outside?
If that's not the case just store it locally and remove the unnecessary code. If that's the case, just create a public method (rather than a variable) that exposes the name by executing `$event->job-> resolveName()` on-demand (if is possible)

2021-01-11 08:33 UTC, houssainy commented on src/WorkerServiceProvider.php
>          });
I agree with @nerac we can have them as private instead of public static (@m-abdelmohsen do you know if `starts` can also be private?)

@nerac regarding creating a public method to expose the name using `$event->job-> resolveName()` this will not work, this is because:
1. This class doesn't have an instance of the $event, and the $event being passed only to the callback function of the defined listeners (line 47 and line 54).
2. Not all the events have an instance of the job (e.g. WorkerStopping the main event that we want to listen on), but we do need the job name to be exported by prometheus whenever any event got fired. As workaround we defined these variables, and since all the jobs pass by Processing state we fetched the needed info in that event, and exported it later when the final event got fired.

This is not the cleanest way to do this and if we want a cleaner way we can have these values stored in redis in Processing event, and retrieve them in the rest of the events, but i feel that then we will be over engineering the problem.

2021-01-11 08:50 UTC, houssainy commented on src/WorkerServiceProvider.php
> +                        $errorCode = -1;
@m-abdelmohsen did you have a chance to check if we can easily restructure the exported data without loosing the old data ? 

@nerac when we tried to add a new exported value that isn't exported before, prometheus didn't know what to do with the old data that doesn't have this value, and accordingly the `/prometheus` returned an error saying that all the data should have the same fields. 
In that case i believe we either create a migration for the old data (if this is feasible) or clearing the old data if they are not needed.

2021-01-11 08:51 UTC, houssainy commented on src/WorkerServiceProvider.php
> +                // fail silently and don't stop the application
Added a log message with the error + reported to bugsnag

2021-01-11 11:14 UTC, m-abdelmohsen commented on src/WorkerServiceProvider.php
> +                        $errorCode = -1;
@nerac that is the default error we can have that status. ultimately we should not be at that switch-case at all

2021-01-11 11:19 UTC, m-abdelmohsen commented on src/WorkerServiceProvider.php
> +                        $errorCode = -1;
I can not see a lot of benefits to splitting that into 2 fields where we have error type and status since I can not think about any more status more than these 4 status.

I have tried to get the status code from the exception as well and send it in case that is a useful infomation

2021-01-12 10:11 UTC, nerac requested changes

2021-01-12 10:11 UTC, nerac commented on src/WorkerServiceProvider.php
> +                        $errorCode = -1;
What I would like to get out of these metrics is the following:

- Total requests
- Success requests
- Error requests
- Error requests by type

Without any of these values, we cannot have a proper SLI IMO.
On another hand I reiterate, a **-1** is not informative so people without context will not understand what they are seeing so they will have to spend time with documentation or with your pals. If we rather use an informative string value we can save a bunch of time and the cost is minimal.

2021-01-12 10:11 UTC, nerac commented on src/WorkerServiceProvider.php
> +    private $connectionName;
I think we should move this to the local method `boot` as we are only using it there, no need to put it at the class level for now.

2021-01-12 10:48 UTC, houssainy commented on src/WorkerServiceProvider.php
> +    private $connectionName;
@nerac and I checked this and we found that the variables in boot method will not be scoped with the listeners anonymous functions (not like we have in JS or Go). and the only way to do that is to use `use` keyword which will be too verbose. 

We will keep this variables at the class level.

2021-01-12 10:55 UTC, nerac commented on src/WorkerServiceProvider.php
> +    private $connectionName;
Correct.

2021-01-12 10:59 UTC, nerac approved these changes

2021-01-12 11:45 UTC, houssainy commented
I will merge this now to create a new release to start monitor the different states of the jobs as appearing in this PR, but we need to find a way to change the exported schema without loosing the old data. 

I am creating a separate ticket for finding a way to do the restructure of the schema.

2021-01-12 11:45 UTC, merged